reload "user.plugins"
reload "user.mason-tool-installer"
reload "user.options"
reload "user.settings"
reload "user.keymaps"
reload "user.autocommands"
reload "user.autopairs"
reload "user.lsp"
reload "user.smoothie"
reload "user.harpoon"
reload "user.autocommands"
reload "user.webdev-icons"
reload "user.cybu"
reload "user.fidget"
reload "user.surround"
reload "user.bookmark"
reload "user.todo-comments"
reload "user.barbar"
reload "user.jaq"
reload "user.fidget"
-- reload "user.lab"
reload "user.git"
reload "user.inlay-hints"
reload "user.telescope"
reload "user.bqf"
reload "user.nvim-notify"
-- reload "user.dial"
reload "user.numb"
reload "user.refactoring"
reload "user.treesitter"
reload "user.colorizer"
reload "user.lualine"
reload "user.scrollbar"
reload "user.whichkey"
-- reload "user.neoai"
reload "user.cmp"
reload "user.nvimtree"
-- reload "nostr"
-- reload "user.astro-tools"
reload "user.matchup"
reload "user.modicator"
